spring:
  application:
    name: spring-boot-developer-test
  
  cassandra:
    keyspace-name: test_keyspace
    contact-points: localhost
    port: 9042
    local-datacenter: datacenter1
    schema-action: create_if_not_exists
  
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: account-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest

external:
  validation:
    url: http://localhost:8089/validate

server:
  port: 8080

logging:
  level:
    com.assessment: DEBUG